
CREATE DATABASE CAD_ANIMAIS;
USE CAD_ANIMAIS; 


CREATE TABLE USUARIOS(
NOME VARCHAR(50) NOT NULL,
IDADE VARCHAR(50),
TELEFONE VARCHAR(50) ,
EMAIL VARCHAR(100),
SENHA VARCHAR(150)
);


CREATE TABLE CACHORRO(
SEXO VARCHAR(50) NOT NULL,
PORTE VARCHAR(50),
IDADE VARCHAR(50),
CASTRADO VARCHAR(4),
DESCRICAO VARCHAR(150),
TELEFONE VARCHAR(50) ,
EMAIL VARCHAR(100),
IMAGEM VARCHAR(220)
);


CREATE TABLE GATO(
SEXO VARCHAR(50) NOT NULL,
IDADE VARCHAR(50),
CASTRADO VARCHAR(4),
DESCRICAO VARCHAR(150),
TELEFONE VARCHAR(50),
EMAIL VARCHAR(100),
IMAGEM VARCHAR(220)
);



CREATE TABLE AVES(
TIPO VARCHAR(50),
SEXO VARCHAR(50),
DESCRICAO VARCHAR(150),
TELEFONE VARCHAR(50) ,
EMAIL VARCHAR(100),
IMAGEM VARCHAR(220)
);


CREATE TABLE OUTROS(
ESPECIE VARCHAR(50) NOT NULL,
TIPO VARCHAR(50),
SEXO VARCHAR(50),
IDADE VARCHAR(50),
CASTRADO VARCHAR(4),
DESCRIÇÃO VARCHAR(150),
TELEFONE VARCHAR(50),
EMAIL VARCHAR(100),
IMAGEM VARCHAR(220)
);


SELECT * FROM CACHORRO;
SELECT * FROM GATO;
SELECT * FROM AVES;
SELECT * FROM OUTROS;
SELECT * FROM USUARIOS;



